### ISSUE TITLE
Add support to require a folder

### ISSUE THREAD

**Issue by darkxeno** [zsoltszabo/node-uglifier#14]
Requiring a folder should load the index.js inside of the folder.

Current error output:

Warning!:
unhandled require type in file: [xxx]/build/index.js the problematic statement: require("./controllers/") probably something fancy going on  the error: in file: [xxx]/build/index.js require for a directory not supported require("./controllers/")

**Comment by zsoltszabo** [comment]
I added directory support now.

**Comment by darkxeno** [comment]
Thanks
