### ISSUE TITLE
Express routes don't work (once they are in a separate file)

### ISSUE THREAD

**Issue by dittmarconsulting** [zsoltszabo/node-uglifier#16]
Hi there,

Love your project. 

I successfully compressed a very simple express test project. Here the layout:

app
-- router
---- router.js
-- node_modules
-- package.json
-- server.js
-- server_compiled.js

Here the content of the server.js

``` javascript
var express = require('express');
var app = express();
require('./router/router.js')(app);
app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

and the content of router.js

``` javascript
module.exports = function(app) {
   app.get('/testroute', function (req, res) {
        res.send('Hello World!');
    });
};
```

If I run the uncompressed **server.js** I can reach the route but once the app is compressed and I run the **server_compiled.js** version I receive the "Cannot GET /testroute" messages as the route didn't exist:

Here the content of the server_compiled.js (beautified)

``` javascript
var cachedModules=[];
cachedModules[2977]={exports:{}},
    function(e,o){
        e.exports=function(e){
            e.get("/testroute",function(e,o){
                o.send("Hello World!")})
        }
    }.call(this,cachedModules[2977],cachedModules[2977].exports);
var express=require("express"), app=express();
cachedModules[2977].exports,
    app.listen(3e3,function(){
        console.log("Example app listening on port 3000!")
    });
//# sourceMappingURL=UGLIFY_SOURCE_MAP_TOKEN_
```

After seeing the uglyfied code it seemed the variable **app** didn't get passed to the module. After I changed the code by hand and added the app variable [**exports(app)**] to the compressed version the app worked as expected.

``` javascript
 ...
var express=require("express"), app=express();
cachedModules[2977].exports(app),
    app.listen(3e3,function(){
...
```

It would be great if you could fix that.

Cheers,
Tom

**Comment by zsoltszabo** [comment]
Hi, you probably moved on for a while, but I checked the code now and it works for me out of the box. I added an express server test case anyways.
So the merged code has this as you wrote as well.
`var express = require("express"), app = express();`
app is global there so no need to pass it down, it is not ES6 let or const
