### ISSUE TITLE
Sugar 2.0 update breaks the code

### ISSUE THREAD

**Issue by skia** [zsoltszabo/node-uglifier#17]
Sugar updated to version 2.0, methods like ".each" are now renamed ".forEach".

Possible fix are both bind the dependencies to 1.x or use the new methods.

**Comment by atishay811** [comment]
Still waiting on this. Is node-uglifier dead?

**Comment by zsoltszabo** [comment]
Hi, I am reborn from the dead. I got a new large project that will need this repo, so patches will be coming again:)
