### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by byteshiva** [zsoltszabo/node-uglifier#21]
I'm getting the below error if I try to run using uglify method, I'm using "  "version": "1.0.0"

```RangeError: Maximum call stack size exceeded```

**Comment by byteshiva** [comment]
http://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded
temp fix
```
/bin/bash -c "ulimit -s 65500; exec /usr/local/bin/node --stack-size=65500 /path/to/app.js"
``

**Comment by zsoltszabo** [comment]
Your project must be huge, how many files?

**Comment by byteshiva** [comment]
its around 3k plus files excluding node_modules files, with total coming LOC around 586055
.

**Comment by zsoltszabo** [comment]
Wow kudos, are you rewriting the internet in Nodejs with that much code? With functional style and coffeescript that amount of code would be enough for a new Operating system. :D

**Comment by byteshiva** [comment]
:-) , my mistake  .. 

well I found the issue, the shell script which runs obfuscation writes the obfuscated code in the same project directory where other application services were located. 

The next run of obfuscation was picking up this obfuscated-code and was trying to process. And I see the your source-code is doing recursion minus tail call optimisation.

which is why the node was throwing out of stack error.

Now that I put the obfuscated code in separate DIST directory, it doesn't break.

**Comment by zsoltszabo** [comment]
Yeah I could remove the recursion if it is a big problem, I always find recursion is more readable albeit not optimized solution. In the end all recursion can be simulated with a stack on the heap.
