### ISSUE TITLE
TypeError: me.cycle.last is not a function

### ISSUE THREAD

**Issue by thomasdavis** [zsoltszabo/node-uglifier#22]
On this line of code
```
edgeToRemove = [me.cycle.last(2).last(), me.cycle.last(2).first()].reverse();
```
I can probably find the fix myself but I am not sure what was intended by [].last.
Where does that method come from? Native JS?

```
console.log(me.cycle); 
// [ '/home/ajax/repos/listium/Listium-web/es5-server/shared/scripts/Jsonify.js',
  '/home/ajax/repos/listium/Listium-web/es5-server/shared/scripts/ListTable.js' ]
```

**Comment by zsoltszabo** [comment]
Hi, I pushed an update for this bug with test. Sugarjs had a major change and have to manually enable extensions like last.
