### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by mfrost66** [zsoltszabo/node-uglifier#4]
It's choking on ES6 syntax currently supported by node v4: `` strings, let keyword etc.

**Comment by zsoltszabo** [comment]
Thanks for letting me know, pull requests are welcome:)

**Comment by AleCaste** [comment]
Same here, I am having problems using generators in my project.
Was this issue taken into account already?

**Comment by zsoltszabo** [comment]
Unfortunately I am alone developing this project and so far I have not needed ES6 features myself.

**Comment by AleCaste** [comment]
Hi!
In your package.json you my use the branch:
```'uglify-js': 'git://github.com/mishoo/UglifyJS2#harmony'```
It is the official uglify branch with support for ES6. It is not finished yet but they are getting there.
There is a more "advanced" fork of this branch that goes a little further with ES6 support:
```'uglify-js': 'git://github.com/UXtemple/UglifyJS2#harmony-generators-yield'```
The above fork adds support for generators but it is not fully working yet (just almost!)
You can give it a go.

By the way, your project is great. In these days I'll send you a pull request to improve the way the final package is built. Your approach to order the js files in the right way is quite good but it fails oncertain scenarios. I have improved the algorithm and will send you the code in the near future.
Great project!
Alex

**Comment by andynq678** [comment]
how to support es6?i can not get my min file when i add generator function like function*

**Comment by zsoltszabo** [comment]
Thanks for the input, I switched to the Harmony branch of Uglifier-Js. Besides like importing, most of the ES6 stuff are supported.
