### ISSUE TITLE
'require' not always resolved correctly

### ISSUE THREAD

**Issue by AyrA** [zsoltszabo/node-uglifier#5]
the following require statement is not recognized by node-uglifier:

```javascript
    var a=require("some-node-module").someFunction();
```

This works:

```javascript
    var a=require("some-node-module");
    a=a.someFunction();
```

An example, where you want to do this, is [the log4js module](https://github.com/nomiddlename/log4js-node), for which you would do

```javascript
var logger=require("log4js").getLogger();
```

Using Version 0.4.3 according to package.json. There seems to be a discrepancy between the actual npm version and the github version

**Comment by zsoltszabo** [comment]
Thanks for letting me know, there are always these edge cases that I never stumble uppon in my 100+ npm libraries included projects.:)
But it should be easy to solve, I will check it out!

**Comment by zsoltszabo** [comment]
Hi I pushed the fix for this case

**Comment by AyrA** [comment]
thank you. Will try this
